!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE 
NULL=nul
!ENDIF 

TARGET=GrcRegressionTest
REGT_SRC=.
REGT_RES=.
GR_FONT=..\..\..\graphite\engine\src\font
GR_SEG=..\..\..\graphite\engine\src\segment


!IF "$(CFG)" == ""
CFG=DEBUG
!ENDIF 

!IF "$(CFG)" == "RELEASE"

OUTDIR=.\release
INTDIR=.\release_temp

all : "$(OUTDIR)\$(TARGET).exe"

clean :
    @- rd /s/q $(INTDIR)
    
realclean : clean
    @- rd /s/q $(OUTDIR)

CPP_PROJ=/nologo /MT /W3 /GR /GX /O2 /I "."  /I "../../compiler"  /I "../../../graphite/engine/include"  /I "../../../graphite/engine/include/graphite"  /I "../../../graphite/engine/src/segment"  /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /D "_UNICODE" /D "UNICODE" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /c 
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\$(TARGET).res" /d "NDEBUG"
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib  /nologo /subsystem:console /incremental:no /machine:I386 /out:"$(OUTDIR)\$(TARGET).exe" /libpath:"..\..\release" 
BSC32_FLAGS=/nologo /o"$(OUTDIR)\$(TARGET).bsc" 

!ELSEIF "$(CFG)" == "DEBUG"

OUTDIR=.\debug
INTDIR=.\debug_temp

all : "$(OUTDIR)\$(TARGET).exe" "$(OUTDIR)\$(TARGET).bsc"

clean :
    @- rd /s/q $(INTDIR)
    
realclean : clean
    @- rd /s/q $(OUTDIR)

CPP_PROJ=/nologo /MTd /W3 /Gm /GR /GX /GZ /ZI /Od  /I "."  /I "../../compiler"  /I "../../../graphite/engine/include"  /I "../../../graphite/engine/include/graphite"  /I "../../../graphite/engine/src/segment"  /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /D "_UNICODE" /D "UNICODE" /FR"$(INTDIR)\\" /Fo"$(INTDIR)\\" /Fd"$(INTDIR)\\" /c 
RSC_PROJ=/l 0x409 /fo"$(INTDIR)\$(TARGET).res" /d "_DEBUG"
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /nologo /subsystem:console /incremental:yes /pdb:"$(OUTDIR)\$(TARGET).pdb" /debug /machine:I386 /out:"$(OUTDIR)\$(TARGET).exe"  /libpath:"..\..\debug" 
BSC32_FLAGS=/nologo /o"$(OUTDIR)\$(TARGET).bsc" 

!ENDIF

"$(OUTDIR)" :
    if not exist "$(OUTDIR)/$(NULL)" mkdir "$(OUTDIR)"

"$(INTDIR)" :
    if not exist "$(INTDIR)/$(NULL)" mkdir "$(INTDIR)"

{$(REGT_SRC)}.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

{$(REGT_SRC)}.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

{$(GR_FONT)}.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

{$(GR_FONT)}.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

{$(GR_SEG)}.cpp{$(INTDIR)}.obj::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<

{$(GR_SEG)}.cpp{$(INTDIR)}.sbr::
   $(CPP) @<<
   $(CPP_PROJ) $< 
<<




CPP=cl.exe
RSC=rc.exe
BSC32=bscmake.exe
LINK32=link.exe

LINK32_OBJS= \
      "$(INTDIR)\GrcRegressionTest.obj" \
      "$(INTDIR)\CompareFontTables.obj" \
      "$(INTDIR)\GrcRtFileFont.obj" \
      "$(INTDIR)\FontStub.obj" \
      "$(INTDIR)\TtfUtil.obj" \
      "$(INTDIR)\FileInput.obj" \
      "$(INTDIR)\Platform.obj" \

	
#	"$(INTDIR)\GrcRegressionTest.res"

"$(OUTDIR)\$(TARGET).exe" : "$(OUTDIR)" $(DEF_FILE) $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<

BSC32_SBRS= \
      "$(INTDIR)\GrcRegressionTest.sbr" \
      "$(INTDIR)\CompareFontTables.sbr" \
      "$(INTDIR)\GrcRtFileFont.sbr" \
      "$(INTDIR)\FontStub.sbr" \
      "$(INTDIR)\TtfUtil.sbr" \
      "$(INTDIR)\FileInput.sbr" \
      "$(INTDIR)\Platform.sbr" \
#

"$(OUTDIR)\$(TARGET).bsc" : "$(OUTDIR)" $(BSC32_SBRS)
    $(BSC32) @<<
  $(BSC32_FLAGS) $(BSC32_SBRS)
<<

"$(INTDIR)\GrcRegressionTest.obj"  "$(INTDIR)\GrcRegressionTest.sbr" : "$(REGT_SRC)\GrcRegressionTest.cpp" "$(INTDIR)"
"$(INTDIR)\CompareFontTables.obj"  "$(INTDIR)\CompareFontTables.sbr" : "$(REGT_SRC)\CompareFontTables.cpp" "$(INTDIR)"
"$(INTDIR)\GrcRtFileFont.obj"  "$(INTDIR)\GrcRtFileFont.sbr" : "$(REGT_SRC)\GrcRtFileFont.cpp" "$(INTDIR)"
"$(INTDIR)\FontStub.obj"  "$(INTDIR)\FontStub.sbr" : "$(REGT_SRC)\FontStub.cpp" "$(INTDIR)"
"$(INTDIR)\TtfUtil.obj"  "$(INTDIR)\TtfUtil.sbr" : "$(GR_FONT)\TtfUtil.cpp" "$(INTDIR)"
"$(INTDIR)\FileInput.obj"  "$(INTDIR)\FileInput.sbr" : "$(GR_SEG)\FileInput.cpp" "$(INTDIR)"
"$(INTDIR)\Platform.obj"  "$(INTDIR)\Platform.sbr" : "$(GR_SEG)\Platform.cpp" "$(INTDIR)"



"$(INTDIR)\$(TARGET).res" : "$(REGT_RES)\$(TARGET).rc" "$(INTDIR)"
	$(RSC) $(RSC_PROJ) "$(REGT_RES)\$(TARGET).rc"

