#ifndef INC_GrpParserTokenTypes_hpp_
#define INC_GrpParserTokenTypes_hpp_

#include "antlr/config.hpp"
/*
 * ANTLR-generated file resulting from grammar c:\silgraphite_2_0\grcompiler\compiler\grpparser.g
 * 
 * Terence Parr, MageLang Institute
 * with John Lilley, Empathy Software
 * ANTLR Version 2.6.0; 1996-1999
 */

enum GrpParserTokenTypes {
	EOF_ = 1,
	NULL_TREE_LOOKAHEAD = 3,
	OP_EQ = 4,
	OP_PLUSEQUAL = 5,
	OP_LPAREN = 6,
	OP_RPAREN = 7,
	OP_SEMI = 8,
	LITERAL_environment = 9,
	LITERAL_endenvironment = 10,
	OP_LBRACE = 11,
	OP_RBRACE = 12,
	IDENT = 13,
	LITERAL_table = 14,
	LITERAL_endtable = 15,
	LITERAL_name = 16,
	LIT_INT = 17,
	OP_DOT = 18,
	OP_PLUS_EQUAL = 19,
	LIT_STRING = 20,
	OP_COMMA = 21,
	LITERAL_string = 22,
	LITERAL_glyph = 23,
	OP_ANDEQUAL = 24,
	OP_MINUSEQUAL = 25,
	LITERAL_pseudo = 26,
	LIT_UHEX = 27,
	LITERAL_codepoint = 28,
	LITERAL_glyphid = 29,
	LITERAL_postscript = 30,
	LITERAL_unicode = 31,
	OP_DOTDOT = 32,
	LIT_CHAR = 33,
	LITERAL_feature = 34,
	LITERAL_language = 35,
	LITERAL_languages = 36,
	LITERAL_substitution = 37,
	LITERAL_pass = 38,
	LITERAL_endpass = 39,
	LITERAL_if = 40,
	LITERAL_else = 41,
	LITERAL_endif = 42,
	Zelseif = 43,
	LITERAL_elseif = 44,
	OP_GT = 45,
	OP_DIV = 46,
	OP_QUESTION = 47,
	OP_LBRACKET = 48,
	OP_RBRACKET = 49,
	OP_UNDER = 50,
	OP_AT = 51,
	OP_COLON = 52,
	OP_HASH = 53,
	OP_DOLLAR = 54,
	Qalias = 55,
	LITERAL_justification = 56,
	LITERAL_position = 57,
	LITERAL_positioning = 58,
	LITERAL_linebreak = 59,
	OP_CARET = 60,
	LITERAL_justify = 61,
	OP_DIVEQUAL = 62,
	OP_MULTEQUAL = 63,
	OP_OR = 64,
	OP_AND = 65,
	OP_EQUALEQUAL = 66,
	OP_NE = 67,
	OP_LT = 68,
	OP_LE = 69,
	OP_GE = 70,
	OP_PLUS = 71,
	OP_MINUS = 72,
	OP_MULT = 73,
	OP_NOT = 74,
	LITERAL_true = 75,
	LITERAL_false = 76,
	LITERAL_max = 77,
	LITERAL_min = 78,
	Zalias = 79,
	Zassocs = 80,
	Zattrs = 81,
	Zcluster = 82,
	Zcodepage = 83,
	Zconstraint = 84,
	Zcontext = 85,
	Zdirectives = 86,
	ZdotStruct = 87,
	Zfeatures = 88,
	Zfunction = 89,
	ZifStruct = 90,
	Zlhs = 91,
	Zlookup = 92,
	Zrhs = 93,
	Zrule = 94,
	ZruleItem = 95,
	Zselector = 96,
	Ztop = 97,
	ZuHex = 98,
	WS = 99,
	COMMENT_SL = 100,
	COMMENT_ML = 101,
	ESC = 102,
	ODIGIT = 103,
	DIGIT = 104,
	XDIGIT = 105,
	SQUOTE = 106,
	DQUOTE = 107,
	OP_LINEMARKER = 108,
	OP_BSLASH = 109,
	AT_IDENT = 110,
};
#endif /*INC_GrpParserTokenTypes_hpp_*/
