#ifndef INC_GrpParserTokenTypes_hpp_
#define INC_GrpParserTokenTypes_hpp_

#include "Antlr/config.hpp"
/*
 * ANTLR-generated file resulting from grammar c:\fw\src\graphite\grcompiler\grpparser.g
 * 
 * Terence Parr, MageLang Institute
 * with John Lilley, Empathy Software
 * ANTLR Version 2.6.0; 1996-1999
 */

enum GrpParserTokenTypes {
	EOF_ = 1,
	NULL_TREE_LOOKAHEAD = 3,
	OP_EQ = 4,
	OP_PLUSEQUAL = 5,
	OP_LPAREN = 6,
	OP_RPAREN = 7,
	OP_SEMI = 8,
	LITERAL_environment = 9,
	LITERAL_endenvironment = 10,
	OP_LBRACE = 11,
	OP_RBRACE = 12,
	IDENT = 13,
	LITERAL_table = 14,
	LITERAL_endtable = 15,
	LITERAL_name = 16,
	LIT_INT = 17,
	OP_DOT = 18,
	OP_PLUS_EQUAL = 19,
	LIT_STRING = 20,
	OP_COMMA = 21,
	LITERAL_string = 22,
	LITERAL_glyph = 23,
	LITERAL_pseudo = 24,
	LIT_UHEX = 25,
	LITERAL_codepoint = 26,
	LITERAL_glyphid = 27,
	LITERAL_postscript = 28,
	LITERAL_unicode = 29,
	OP_DOTDOT = 30,
	LIT_CHAR = 31,
	LITERAL_feature = 32,
	LITERAL_substitution = 33,
	LITERAL_pass = 34,
	LITERAL_endpass = 35,
	LITERAL_if = 36,
	LITERAL_else = 37,
	LITERAL_endif = 38,
	Zelseif = 39,
	LITERAL_elseif = 40,
	OP_GT = 41,
	OP_DIV = 42,
	OP_QUESTION = 43,
	OP_LBRACKET = 44,
	OP_RBRACKET = 45,
	OP_UNDER = 46,
	OP_AT = 47,
	OP_COLON = 48,
	OP_HASH = 49,
	OP_DOLLAR = 50,
	Qalias = 51,
	LITERAL_justification = 52,
	LITERAL_position = 53,
	LITERAL_positioning = 54,
	LITERAL_linebreak = 55,
	OP_CARET = 56,
	OP_MINUSEQUAL = 57,
	OP_DIVEQUAL = 58,
	OP_MULTEQUAL = 59,
	OP_OR = 60,
	OP_AND = 61,
	OP_EQUALEQUAL = 62,
	OP_NE = 63,
	OP_LT = 64,
	OP_LE = 65,
	OP_GE = 66,
	OP_PLUS = 67,
	OP_MINUS = 68,
	OP_MULT = 69,
	OP_NOT = 70,
	LITERAL_true = 71,
	LITERAL_false = 72,
	LITERAL_max = 73,
	LITERAL_min = 74,
	Zalias = 75,
	Zassocs = 76,
	Zattrs = 77,
	Zcluster = 78,
	Zcodepage = 79,
	Zconstraint = 80,
	Zcontext = 81,
	Zdirectives = 82,
	ZdotStruct = 83,
	Zfeatures = 84,
	Zfunction = 85,
	ZifStruct = 86,
	Zlhs = 87,
	Zlookup = 88,
	Zrhs = 89,
	Zrule = 90,
	ZruleItem = 91,
	Zselector = 92,
	Ztop = 93,
	ZuHex = 94,
	WS = 95,
	COMMENT_SL = 96,
	COMMENT_ML = 97,
	ESC = 98,
	ODIGIT = 99,
	DIGIT = 100,
	XDIGIT = 101,
	SQUOTE = 102,
	DQUOTE = 103,
	OP_LINEMARKER = 104,
	OP_BSLASH = 105,
	AT_IDENT = 106,
};
#endif /*INC_GrpParserTokenTypes_hpp_*/

